apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: devtest
  labels:
    app: myappnameLabel
    naber: test1naber-custom
spec:
  containers:
    - name: nginx-container
      image: nginx
      command: ["sleep2.0"]
      args: ["10"]
