apiVersion: v1
kind: ReplicaController
metadata:
  name: some-rep-controller
  labels:
    app: rep-controller
    type: frontend-controller
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myappnameLabel
        naber: test1naber-custom
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3