apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    label: some-label
  name: volume-test
spec:
  containers: 
  - image: nginx
    name: pod
    volumeMounts:
    - mountPath: /opt
      name: data-vol 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: data-vol
    hostPath:
      path: /Users/voltest
      type: Directory
status: {}
